bot:
  token: "DUMMY"        # not used now
  mode: "polling"
  port: 9000
  url: "http://localhost:9000"
  admin_ids:
    - 100318530

admin:
  port: 9090

database:
  url: "postgres://postgres:postgres@127.0.0.1:5432/subscription_test?sslmode=disable"

redis:
  url: "redis://localhost:6379"
  password: ""
  db: 1
  ttl: "1h"

ai:
  openai_key: "sk-..."
  gemini_key: ""
  gemini_url: "https://generativelanguage.googleapis.com"
  default_model: "gpt-4"

payment:
  mellat_terminal: "TERMINAL123"
  zarinpal_key: "ZP-KEY-XYZ"

scheduler:
  expiry_check_cron: "0 0 * * *"
