services:
  postgres:
    image: postgres:14
    container_name: ai-bot-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_test
      TZ: Asia/Tehran
      PGTZ: Asia/Tehran
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - postgres
      - "-c"
      - "listen_addresses=*"

volumes:
  postgres_data:
