services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: telegram-ai:debug
    container_name: telegram-ai-debug
    volumes:
      - ./:/src
      - ./config.yaml:/etc/app/config.yaml:ro
    ports:
      - "127.0.0.1:40000:40000"
      - "8080:8080"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    depends_on:
      - postgres
      - redis